# Generated by Django 2.0.2 on 2018-02-19 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 19, 15, 32, 45, 384959, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
